packages:
  - apps/*
  - packages/*

saveExact: true
strictPeerDependencies: true
autoInstallPeers: true
allowBuilds:
  cpu-features: false
  esbuild: true
  protobufjs: true
  ssh2: false
  workerd: true
