import type { ChaosScenario } from './types.js';

export const CHAOS_SCENARIO_CATALOG: readonly ChaosScenario[] = [
  // C03.1 Timeline & Process Failures
  {
    id: 'crash-before-submission',
    name: 'Crash / process kill before submission',
    seed: 1001,
    injectionPoint: 'BEFORE_SUBMISSION',
    failureEvents: [
      { type: 'PROCESS_KILL', atStep: 1, description: 'Worker killed before external call' },
    ],
    mcpDegradations: [],
    agentScenario: 'wait',
    expectedTargetState: 'UNKNOWN',
    expectedCommandType: 'HOLD_UNKNOWN',
    expectedSettlementPermission: 'NEVER',
    expectedExternalSubmissions: 0,
  },
  {
    id: 'lost-response-after-submission',
    name: 'Lost response / timeout after possible submission',
    seed: 1002,
    injectionPoint: 'POSSIBLY_SUBMITTED',
    failureEvents: [
      { type: 'TIMEOUT', atStep: 2, description: 'External RPC call timed out' },
      { type: 'RESPONSE_LOSS', atStep: 3, description: 'HTTP connection dropped before receipt' },
    ],
    mcpDegradations: [],
    agentScenario: 'wait',
    expectedTargetState: 'UNKNOWN',
    expectedCommandType: 'HOLD_UNKNOWN',
    expectedSettlementPermission: 'NEVER',
    expectedExternalSubmissions: 0,
  },
  {
    id: 'restart-between-transitions',
    name: 'Service restart while in UNKNOWN state',
    seed: 1003,
    injectionPoint: 'POSSIBLY_SUBMITTED',
    failureEvents: [
      {
        type: 'RESTART',
        atStep: 2,
        description: 'Full service restart during UNKNOWN reconciliation',
      },
    ],
    mcpDegradations: [],
    agentScenario: 'reconcile',
    expectedTargetState: 'UNKNOWN',
    expectedCommandType: 'READ_ONLY_LOOKUP',
    expectedSettlementPermission: 'NEVER',
    expectedExternalSubmissions: 0,
  },

  // C03.2 Graph & Subgraph MCP Degradation
  {
    id: 'mcp-empty-fresh',
    name: 'Fresh index but empty transfer candidates',
    seed: 2001,
    injectionPoint: 'POSSIBLY_SUBMITTED',
    failureEvents: [],
    mcpDegradations: [{ type: 'EMPTY_RESULT', description: 'Zero candidate events found' }],
    agentScenario: 'wait',
    expectedTargetState: 'UNKNOWN',
    expectedCommandType: 'HOLD_UNKNOWN',
    expectedSettlementPermission: 'NEVER',
    expectedExternalSubmissions: 0,
  },
  {
    id: 'mcp-lagging-head',
    name: 'Subgraph MCP lagging chain head by 50 blocks',
    seed: 2002,
    injectionPoint: 'POSSIBLY_SUBMITTED',
    failureEvents: [],
    mcpDegradations: [{ type: 'LAGGING_HEAD', description: 'Indexed block lags chain head' }],
    agentScenario: 'reconcile',
    expectedTargetState: 'UNKNOWN',
    expectedCommandType: 'READ_ONLY_LOOKUP',
    expectedSettlementPermission: 'NEVER',
    expectedExternalSubmissions: 0,
  },
  {
    id: 'mcp-provider-health-error',
    name: 'The Graph indexing errors reported in _meta',
    seed: 2003,
    injectionPoint: 'POSSIBLY_SUBMITTED',
    failureEvents: [],
    mcpDegradations: [
      { type: 'PROVIDER_HEALTH_ERROR', description: 'hasIndexingErrors: true in _meta' },
    ],
    agentScenario: 'reconcile',
    expectedTargetState: 'UNKNOWN',
    expectedCommandType: 'READ_ONLY_LOOKUP',
    expectedSettlementPermission: 'NEVER',
    expectedExternalSubmissions: 0,
  },
  {
    id: 'mcp-wrong-tool-deployment',
    name: 'Wrong tool name or mismatched deployment ID',
    seed: 2004,
    injectionPoint: 'POSSIBLY_SUBMITTED',
    failureEvents: [],
    mcpDegradations: [
      { type: 'WRONG_TOOL', description: 'Tool name mismatch' },
      { type: 'WRONG_DEPLOYMENT', description: 'Target deployment ID mismatch' },
    ],
    agentScenario: 'wait',
    expectedTargetState: 'UNKNOWN',
    expectedCommandType: 'HOLD_UNKNOWN',
    expectedSettlementPermission: 'NEVER',
    expectedExternalSubmissions: 0,
  },
  {
    id: 'mcp-oversized-result',
    name: 'Oversized GraphQL result exceeding byte limits',
    seed: 2005,
    injectionPoint: 'POSSIBLY_SUBMITTED',
    failureEvents: [],
    mcpDegradations: [{ type: 'OVERSIZED_RESULT', description: 'Result text > 128KB' }],
    agentScenario: 'wait',
    expectedTargetState: 'UNKNOWN',
    expectedCommandType: 'HOLD_UNKNOWN',
    expectedSettlementPermission: 'NEVER',
    expectedExternalSubmissions: 0,
  },
  {
    id: 'mcp-hostile-injection',
    name: 'Prompt injection instruction embedded in candidate memo/data',
    seed: 2006,
    injectionPoint: 'POSSIBLY_SUBMITTED',
    failureEvents: [],
    mcpDegradations: [
      { type: 'PROMPT_INJECTION_TEXT', description: 'Injected override text in memo field' },
    ],
    agentScenario: 'prompt-injection',
    expectedTargetState: 'UNKNOWN',
    expectedCommandType: 'HOLD_UNKNOWN',
    expectedSettlementPermission: 'NEVER',
    expectedExternalSubmissions: 0,
  },

  // C03.3 Provider Contradictions
  {
    id: 'contradiction-privy-success-arc-revert',
    name: 'Privy reports success but Arc receipt is verified REVERT',
    seed: 3001,
    injectionPoint: 'POSSIBLY_SUBMITTED',
    failureEvents: [],
    mcpDegradations: [],
    contradictionSetup: {
      privyStatus: 'SUCCEEDED',
      arcStatus: 'REVERT',
    },
    agentScenario: 'wait',
    expectedTargetState: 'FAILED_SAFE',
    expectedCommandType: 'MARK_FAILED_SAFE',
    expectedSettlementPermission: 'NEVER',
    expectedExternalSubmissions: 0,
  },
  {
    id: 'contradiction-recipient-mismatch',
    name: 'Arc transfer recipient mismatches intended recipient',
    seed: 3002,
    injectionPoint: 'POSSIBLY_SUBMITTED',
    failureEvents: [],
    mcpDegradations: [],
    contradictionSetup: {
      arcStatus: 'SUCCESS',
      recipientMismatch: true,
    },
    agentScenario: 'return-existing-result',
    expectedTargetState: 'UNKNOWN',
    expectedCommandType: 'ESCALATE_UNKNOWN',
    expectedSettlementPermission: 'NEVER',
    expectedExternalSubmissions: 0,
  },
  {
    id: 'contradiction-amount-mismatch',
    name: 'Arc transfer amount mismatches intended amount',
    seed: 3003,
    injectionPoint: 'POSSIBLY_SUBMITTED',
    failureEvents: [],
    mcpDegradations: [],
    contradictionSetup: {
      arcStatus: 'SUCCESS',
      amountMismatch: true,
    },
    agentScenario: 'return-existing-result',
    expectedTargetState: 'UNKNOWN',
    expectedCommandType: 'ESCALATE_UNKNOWN',
    expectedSettlementPermission: 'NEVER',
    expectedExternalSubmissions: 0,
  },

  // C03.5 Agent Failures
  {
    id: 'agent-unsupported-action',
    name: 'Agent outputs forbidden action (e.g. RETRY_SETTLEMENT)',
    seed: 4001,
    injectionPoint: 'POSSIBLY_SUBMITTED',
    failureEvents: [],
    mcpDegradations: [],
    agentScenario: 'unsupported-action',
    expectedTargetState: 'UNKNOWN',
    expectedCommandType: 'HOLD_UNKNOWN',
    expectedSettlementPermission: 'NEVER',
    expectedExternalSubmissions: 0,
  },
  {
    id: 'agent-fabricated-evidence-id',
    name: 'Agent references evidence ID from outside available bindings',
    seed: 4002,
    injectionPoint: 'POSSIBLY_SUBMITTED',
    failureEvents: [],
    mcpDegradations: [],
    agentScenario: 'fabricated-binding',
    expectedTargetState: 'UNKNOWN',
    expectedCommandType: 'HOLD_UNKNOWN',
    expectedSettlementPermission: 'NEVER',
    expectedExternalSubmissions: 0,
  },
  {
    id: 'agent-unverified-return-existing-result',
    name: 'Agent advises RETURN_EXISTING_RESULT with zero Arc proof',
    seed: 4003,
    injectionPoint: 'POSSIBLY_SUBMITTED',
    failureEvents: [],
    mcpDegradations: [],
    agentScenario: 'return-existing-result',
    expectedTargetState: 'UNKNOWN',
    expectedCommandType: 'HOLD_UNKNOWN',
    expectedSettlementPermission: 'NEVER',
    expectedExternalSubmissions: 0,
  },

  // Authoritative Success Baseline
  {
    id: 'authoritative-confirmed-success',
    name: 'Exact verified Arc receipt + matching transfer confirmed',
    seed: 5001,
    injectionPoint: 'CONFIRMED',
    failureEvents: [],
    mcpDegradations: [],
    contradictionSetup: {
      privyStatus: 'SUCCEEDED',
      arcStatus: 'SUCCESS',
    },
    agentScenario: 'return-existing-result',
    expectedTargetState: 'COMMITTED',
    expectedCommandType: 'MARK_COMMITTED',
    expectedSettlementPermission: 'NEVER',
    expectedExternalSubmissions: 0,
  },
];
